### ISSUE TITLE
redux-logger message

### ISSUE THREAD

**Issue by nico2che** [lonestone/redux-zap#9]
Thanks for this package!

I used to use redux with [redux-logger](https://github.com/LogRocket/redux-logger) and their [titleFormatter](https://github.com/LogRocket/redux-logger#titleformatter--action-object-time-string-took-number--title) option displays `action.type` by default, meanwhile yours is a prefix + namespace which is not really easy to know what's happening

Could it be possible to add zap name to the action type?

**Comment by Godefroy** [comment]
Hi nico2che, thank you for your feedback.

I just published a new version (0.3.1) including better action types.
Does it fit your needs?

**Comment by nico2che** [comment]
Sounds nice! Thank you!
